GET http://localhost:4000/usuarios

###

GET http://localhost:4000/usuarios/1


POST  http://localhost:4000/usuarios
Content-Type: application/json

###

PUT   http://localhost:4000/usuarios/1
Content-Type: application/json


###

DELETE    http://localhost:4000/usuarios/1
Content-Type: application/json